AWSTemplateFormatVersion: "2010-09-09"
Description: URL Shortner

# ----------------- Parameters -----------------
Resources:
  DynamoDBTableUrlshortenertable:
    UpdateReplacePolicy: Retain
    Type: AWS::DynamoDB::Table
    DeletionPolicy: Delete
    Properties:
      SSESpecification:
        SSEEnabled: false
      TableName: url-shortener-table
      AttributeDefinitions:
        - AttributeType: S
          AttributeName: shortcode
      ContributorInsightsSpecification:
        Enabled: false
      BillingMode: PAY_PER_REQUEST
      PointInTimeRecoverySpecification:
        PointInTimeRecoveryEnabled: false
      WarmThroughput:
        ReadUnitsPerSecond: 12000
        WriteUnitsPerSecond: 4000
      KeySchema:
        - KeyType: HASH
          AttributeName: shortcode
      DeletionProtectionEnabled: false
      TableClass: STANDARD
      Tags: []
      TimeToLiveSpecification:
        Enabled: false

  IAMRoleCreateShortURLLambdaRole:
    UpdateReplacePolicy: Retain
    Type: AWS::IAM::Role
    DeletionPolicy: Delete
    Properties:
      Path: /
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      MaxSessionDuration: 3600
      RoleName: CreateShortURLLambdaRole
      Description: Allows Lambda functions to call AWS services on your behalf.
      Policies:
        - PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Resource: !GetAtt DynamoDBTableUrlshortenertable.Arn
                Action:
                  - dynamodb:PutItem
                  - dynamodb:UpdateItem
                Effect: Allow
                Sid: VisualEditor0
          PolicyName: CreateShortURLLambdaRolePolicy
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Action: sts:AssumeRole
            Effect: Allow
            Principal:
              Service: lambda.amazonaws.com

  IAMRoleRedirectLambdaRole:
    UpdateReplacePolicy: Retain
    Type: AWS::IAM::Role
    DeletionPolicy: Delete
    Properties:
      Path: /
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      MaxSessionDuration: 3600
      RoleName: RedirectLambdaRole
      Description: Allows Lambda functions to call AWS services on your behalf.
      Policies:
        - PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Resource: !GetAtt DynamoDBTableUrlshortenertable.Arn
                Action:
                  - dynamodb:GetItem
                  - dynamodb:Query
                Effect: Allow
                Sid: VisualEditor0
          PolicyName: RedirectLambdaRolePolicy
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Action: sts:AssumeRole
            Effect: Allow
            Principal:
              Service: lambda.amazonaws.com

  CreateShortURL:
    UpdateReplacePolicy: Retain
    DeletionPolicy: Delete
    Type: AWS::Lambda::Function
    Properties:
      Architectures:
        - x86_64
      Code:
        S3Bucket: cc-demo-bucket-p1-263846838953-us-east-1-an
        S3Key: create-short-url.zip
      Description: ""
      EphemeralStorage:
        Size: 512
      Handler: index.handler
      LoggingConfig:
        LogFormat: Text
        LogGroup: /aws/lambda/CreateShortURL
      MemorySize: 128
      PackageType: Zip
      RecursiveLoop: Terminate
      Runtime: nodejs24.x
      RuntimeManagementConfig:
        UpdateRuntimeOn: Auto
      SnapStart:
        ApplyOn: None
      Timeout: 30
      Role: !GetAtt IAMRoleCreateShortURLLambdaRole.Arn

  RedirectToOriginal:
    UpdateReplacePolicy: Retain
    DeletionPolicy: Delete
    Type: AWS::Lambda::Function
    Properties:
      Architectures:
        - x86_64
      Code:
        S3Bucket: cc-demo-bucket-p1-263846838953-us-east-1-an
        S3Key: redirect-to-original.zip
      Description: ""
      EphemeralStorage:
        Size: 512
      Handler: index.handler
      LoggingConfig:
        LogFormat: Text
        LogGroup: /aws/lambda/RedirectToOriginal
      MemorySize: 128
      PackageType: Zip
      RecursiveLoop: Terminate
      Runtime: nodejs24.x
      RuntimeManagementConfig:
        UpdateRuntimeOn: Auto
      SnapStart:
        ApplyOn: None
      Timeout: 30
      Role: !GetAtt IAMRoleRedirectLambdaRole.Arn

  ApiGatewayV2RouteLn:
    UpdateReplacePolicy: Retain
    Type: AWS::ApiGatewayV2::Route
    DeletionPolicy: Delete
    Properties:
      Target: integrations/vy2kzo2
      RequestModels: {}
      AuthorizationScopes: []
      ApiKeyRequired: false
      RouteKey: POST /shorten
      AuthorizationType: NONE
      ApiId: mwraaebttk

  ApiGatewayV2Api:
    UpdateReplacePolicy: Retain
    Type: AWS::ApiGatewayV2::Api
    DeletionPolicy: Delete
    Properties:
      IpAddressType: ipv4
      RouteSelectionExpression: $request.method $request.path
      DisableExecuteApiEndpoint: false
      ProtocolType: HTTP
      Tags: {}
      Name: url-shortener-api

  LambdaPermissionFunctionCreateShortURL:
    UpdateReplacePolicy: Retain
    Type: AWS::Lambda::Permission
    DeletionPolicy: Delete
    Properties:
      FunctionName: arn:aws:lambda:us-east-1:263846838953:function:CreateShortURL
      Action: lambda:InvokeFunction
      SourceArn: arn:aws:execute-api:us-east-1:263846838953:mwraaebttk/*/*/shorten
      Principal: apigateway.amazonaws.com

  ApiGatewayV2IntegrationN9:
    UpdateReplacePolicy: Retain
    Type: AWS::ApiGatewayV2::Integration
    DeletionPolicy: Delete
    Properties:
      IntegrationUri: arn:aws:lambda:us-east-1:263846838953:function:CreateShortURL
      PayloadFormatVersion: "2.0"
      ConnectionType: INTERNET
      RequestTemplates: {}
      ResponseParameters: {}
      TimeoutInMillis: 30000
      ApiId: mwraaebttk
      IntegrationMethod: POST
      IntegrationType: AWS_PROXY

  ApiGatewayV2Route:
    UpdateReplacePolicy: Retain
    Type: AWS::ApiGatewayV2::Route
    DeletionPolicy: Delete
    Properties:
      Target: integrations/sxu65j8
      RequestModels: {}
      AuthorizationScopes: []
      ApiKeyRequired: false
      RouteKey: GET /{shortcode}
      AuthorizationType: NONE
      ApiId: mwraaebttk

  ApiGatewayV2Integration:
    UpdateReplacePolicy: Retain
    Type: AWS::ApiGatewayV2::Integration
    DeletionPolicy: Delete
    Properties:
      IntegrationUri: arn:aws:lambda:us-east-1:263846838953:function:RedirectToOriginal
      PayloadFormatVersion: "2.0"
      ConnectionType: INTERNET
      RequestTemplates: {}
      ResponseParameters: {}
      TimeoutInMillis: 30000
      ApiId: mwraaebttk
      IntegrationMethod: POST
      IntegrationType: AWS_PROXY

  LambdaPermissionFunctionRedirectToOriginal:
    UpdateReplacePolicy: Retain
    Type: AWS::Lambda::Permission
    DeletionPolicy: Delete
    Properties:
      FunctionName: arn:aws:lambda:us-east-1:263846838953:function:RedirectToOriginal
      Action: lambda:InvokeFunction
      SourceArn: arn:aws:execute-api:us-east-1:263846838953:mwraaebttk/*/*/{shortcode}
      Principal: apigateway.amazonaws.com

  CloudFrontDistribution:
    UpdateReplacePolicy: Retain
    Type: AWS::CloudFront::Distribution
    DeletionPolicy: Delete
    Properties:
      DistributionConfig:
        Logging:
          IncludeCookies: false
          Bucket: ""
          Prefix: ""
        Comment: ""
        DefaultRootObject: index.html
        Origins:
          - ConnectionTimeout: 10
            OriginAccessControlId: E1S7ZZV26LDPGB
            ConnectionAttempts: 3
            OriginCustomHeaders: []
            DomainName: sniplink-frontend.s3.us-east-1.amazonaws.com
            OriginShield:
              Enabled: false
            S3OriginConfig:
              OriginReadTimeout: 30
              OriginAccessIdentity: ""
            OriginPath: ""
            Id: sniplink-frontend.s3.us-east-1.amazonaws.com-mq9qv0intp4
          - Id: url-shortener-api
            DomainName: mwraaebttk.execute-api.us-east-1.amazonaws.com
            CustomOriginConfig:
              OriginProtocolPolicy: https-only
              OriginSSLProtocols:
                - TLSv1.2
        ViewerCertificate:
          MinimumProtocolVersion: TLSv1.2_2021
          SslSupportMethod: sni-only
          AcmCertificateArn: arn:aws:acm:us-east-1:263846838953:certificate/b96d4d9c-52ae-4fec-8f19-612e2b5e7bc3
        PriceClass: PriceClass_All
        DefaultCacheBehavior:
          Compress: true
          FunctionAssociations: []
          LambdaFunctionAssociations: []
          TargetOriginId: url-shortener-api
          ViewerProtocolPolicy: redirect-to-https
          GrpcConfig:
            Enabled: false
          TrustedSigners: []
          FieldLevelEncryptionId: ""
          TrustedKeyGroups: []
          AllowedMethods:
            - HEAD
            - DELETE
            - POST
            - GET
            - OPTIONS
            - PUT
            - PATCH
          CachedMethods:
            - HEAD
            - GET
          SmoothStreaming: false
          CachePolicyId: 658327ea-f89d-4fab-a63d-7e88639e58f6
        Staging: false
        CustomErrorResponses: []
        ContinuousDeploymentPolicyId: ""
        OriginGroups:
          Quantity: 0
          Items: []
        Enabled: true
        Aliases:
          - snip.rsarkhel.com
        IPV6Enabled: true
        WebACLId: arn:aws:wafv2:us-east-1:263846838953:global/webacl/CreatedByCloudFront-da2b325f/daa9379e-8bb1-4bbb-ab23-d7cbecdd8ef0
        HttpVersion: http2
        Restrictions:
          GeoRestriction:
            Locations: []
            RestrictionType: none
        CacheBehaviors:
          - PathPattern: /index.html
            TargetOriginId: sniplink-frontend.s3.us-east-1.amazonaws.com-mq9qv0intp4
            ViewerProtocolPolicy: redirect-to-https
            CachePolicyId: 658327ea-f89d-4fab-a63d-7e88639e58f6
            AllowedMethods:
              - HEAD
              - GET
            CachedMethods:
              - HEAD
              - GET
            Compress: true
            SmoothStreaming: false
          - PathPattern: /assets/*
            TargetOriginId: sniplink-frontend.s3.us-east-1.amazonaws.com-mq9qv0intp4
            ViewerProtocolPolicy: redirect-to-https
            CachePolicyId: 658327ea-f89d-4fab-a63d-7e88639e58f6
            AllowedMethods:
              - HEAD
              - GET
            CachedMethods:
              - HEAD
              - GET
            Compress: true
            SmoothStreaming: false
          - PathPattern: /favicon.svg
            TargetOriginId: sniplink-frontend.s3.us-east-1.amazonaws.com-mq9qv0intp4
            ViewerProtocolPolicy: redirect-to-https
            CachePolicyId: 658327ea-f89d-4fab-a63d-7e88639e58f6
            AllowedMethods:
              - HEAD
              - GET
            CachedMethods:
              - HEAD
              - GET
            Compress: true
            SmoothStreaming: false
      Tags:
        - Value: Sniplink-distribution
          Key: Name

  CloudFrontOriginAccessControl:
    UpdateReplacePolicy: Retain
    Type: AWS::CloudFront::OriginAccessControl
    DeletionPolicy: Delete
    Properties:
      OriginAccessControlConfig:
        SigningBehavior: always
        Description: ""
        SigningProtocol: sigv4
        OriginAccessControlOriginType: s3
        Name: sniplink-frontend.s3.us-east-1.amazonaws.com

  S3BucketSniplinkfrontend:
    UpdateReplacePolicy: Retain
    Type: AWS::S3::Bucket
    DeletionPolicy: Delete
    Properties:
      AbacStatus: Disabled
      WebsiteConfiguration:
        IndexDocument: index.html
        ErrorDocument: index.html
      PublicAccessBlockConfiguration:
        RestrictPublicBuckets: true
        IgnorePublicAcls: true
        BlockPublicPolicy: true
        BlockPublicAcls: true
      BucketName: sniplink-frontend
      OwnershipControls:
        Rules:
          - ObjectOwnership: BucketOwnerEnforced
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - BucketKeyEnabled: true
            BlockedEncryptionTypes:
              EncryptionType:
                - SSE-C
            ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256

  S3BucketPolicySniplinkfrontend:
    UpdateReplacePolicy: Retain
    Type: AWS::S3::BucketPolicy
    DeletionPolicy: Delete
    Properties:
      Bucket: sniplink-frontend
      PolicyDocument:
        Version: "2008-10-17"
        Statement:
          - Condition:
              StringEquals:
                AWS:SourceArn: arn:aws:cloudfront::263846838953:distribution/E2WN2KCMZOO0Q5
            Resource: arn:aws:s3:::sniplink-frontend/*
            Action: s3:GetObject
            Effect: Allow
            Principal:
              Service: cloudfront.amazonaws.com
            Sid: AllowCloudFrontServicePrincipal
        Id: PolicyForCloudFrontPrivateContent
